### ISSUE TITLE
Websocket issue while using docker

### ISSUE THREAD

**Issue by nandubatchu** [LavaMoat/ecdsa-wasm#46]
Seeing the following error on browser console on page load: ```index.js:2 WebSocket connection to 'wss://0.0.0.0/demo' failed: ```

**Comment by tmpfs** [comment]
Hi @nandubatchu ,

It is not setup to run wss:// locally at the moment, the code that builds the URL is here:

https://github.com/LavaMoat/ecdsa-wasm/blob/main/client/webpack.config.js#L4-L7

If you access it via `http://localhost:8080` when running the client via `yarn start` it should connect to `ws://localhost:3030/demo` ok (assuming you have started the server!).

**Comment by tmpfs** [comment]
@nandubatchu I am going to close this as I don't think this is a problem. Feel free to open new issues if you have questions or other problems.
